### ISSUE TITLE
handling no rate law case

### ISSUE THREAD

**Issue by longxf21** [ModelEngineering/SBMLKinetics#6]
If one reaction does not have rate law, None will be passed in as parameter when constructing a KineticLaw object.
See line 31 in kinetic_law.py:
    self.formula = self.libsbml_kinetics.getFormula()
AttributeError: 'NoneType' object has no attribute 'getFormula'

**Comment by SunnyXu** [comment]
Hi, Thanks for pointing out this. I have made an update: https://github.com/ModelEngineering/SBMLKinetics/blob/master/SBMLKinetics/common/kinetic_law.py#L31
Please let me know if this is not enough to fix the issue.
